#!/usr/bin/env python3

import argparse
import os

def main():
    parser = argparse.ArgumentParser(
        description="Configure boot mode: GUI or no GUI.")
    parser.add_argument("-d", "--default", required=True,
        choices=["gui", "nogui"], help="Boot mode to set as default.")
    parser.add_argument("-r", "--reboot", action="store_true",
        help="Reboot host once the mode has been changed.")
    args = parser.parse_args()

    if os.getuid() != 0:
        print("Please, run as root")
        return

    targets = {
        "gui": "graphical.target",
        "nogui": "multi-user.target"
    }

    os.system(f"systemctl set-default {targets[args.default]}")

    if args.reboot:
        os.system("reboot")


if __name__ == "__main__":
    main()
